# Generated by Django 5.1.7 on 2025-07-12 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "display_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("color", models.CharField(max_length=20)),
                ("image", models.ImageField(upload_to="projects/main_images/")),
                ("utilization", models.CharField(max_length=255)),
                ("services", models.CharField(max_length=255)),
                ("year", models.CharField(max_length=10)),
                ("category", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=100)),
                ("size", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=50)),
                ("featured", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True, null=True)),
                ("features", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="projects/extra_images/")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="admin_api.project",
                    ),
                ),
            ],
        ),
    ]
