# Generated by Django 5.1.7 on 2025-07-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("category", models.CharField(max_length=100)),
                ("read_time", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="blogs/main_images/")),
                ("summary", models.TextField()),
                ("content", models.TextField()),
                ("tags", models.JSONField(blank=True, null=True)),
                ("featured", models.BooleanField(default=False)),
            ],
        ),
    ]
