# Generated by Django 5.1.7 on 2025-07-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_api", "0003_bloglikefavorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="favorite_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="blog",
            name="like_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
