# Generated by Django 5.2.4 on 2025-07-14 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0004_blog_favorite_count_blog_like_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bloglikefavorite',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='bloglikefavorite',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_favorites', to='admin_api.blog'),
        ),
        migrations.AddIndex(
            model_name='bloglikefavorite',
            index=models.Index(fields=['blog'], name='admin_api_b_blog_id_2d7bd8_idx'),
        ),
        migrations.RemoveField(
            model_name='bloglikefavorite',
            name='user',
        ),
    ]
