# Generated by Django 5.2.4 on 2025-07-14 14:17

import admin_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0005_alter_bloglikefavorite_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloglikefavorite',
            name='visitor_id',
            field=models.CharField(default=admin_api.models.generate_default_visitor_id, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='bloglikefavorite',
            unique_together={('blog', 'visitor_id')},
        ),
        migrations.AddIndex(
            model_name='bloglikefavorite',
            index=models.Index(fields=['visitor_id'], name='admin_api_b_visitor_ffbc3d_idx'),
        ),
    ]
