# Generated by Django 5.2.3 on 2025-07-14 21:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0006_bloglikefavorite_visitor_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('residential', 'Residencial'), ('commercial', 'Comercial'), ('industrial', 'Industrial'), ('specialized', 'Especializado')], max_length=50)),
                ('style', models.CharField(choices=[('modern', 'Moderno'), ('contemporary', 'Contemporáneo'), ('traditional', 'Tradicional'), ('minimalist', 'Minimalista'), ('industrial', 'Industrial')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('area_m2', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('rooms', models.PositiveIntegerField(default=1)),
                ('bathrooms', models.PositiveIntegerField(default=1)),
                ('floors', models.PositiveIntegerField(default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='marketplace/products/')),
                ('features', models.JSONField(default=list)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
