# Generated by Django 5.2.4 on 2025-07-25 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0007_marketplaceproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceproduct',
            name='included_items',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='marketplaceproduct',
            name='not_included_items',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='marketplaceproduct',
            name='price_editable_m2',
            field=models.DecimalField(decimal_places=2, default=1500, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='marketplaceproduct',
            name='price_editable_sqft',
            field=models.DecimalField(decimal_places=2, default=1500, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='marketplaceproduct',
            name='price_pdf_m2',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='marketplaceproduct',
            name='price_pdf_sqft',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
