# Generated by Django 5.2.3 on 2025-07-19 23:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0007_marketplaceproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceproduct',
            name='area_ft2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
