# Generated by Django 5.2.3 on 2025-07-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0008_marketplaceproduct_area_ft2'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceproduct',
            name='ceiling_height_first',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='marketplaceproduct',
            name='ceiling_height_lower',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='marketplaceproduct',
            name='depth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='marketplaceproduct',
            name='foundation_type',
            field=models.CharField(default='Walkout', max_length=50),
        ),
        migrations.AddField(
            model_name='marketplaceproduct',
            name='garage_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='marketplaceproduct',
            name='garage_cars',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='marketplaceproduct',
            name='garage_entry',
            field=models.CharField(default='Front', max_length=50),
        ),
        migrations.AddField(
            model_name='marketplaceproduct',
            name='garage_type',
            field=models.CharField(default='Attached', max_length=50),
        ),
        migrations.AddField(
            model_name='marketplaceproduct',
            name='max_ridge_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='marketplaceproduct',
            name='optional_lower_level',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='marketplaceproduct',
            name='porch_front_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='marketplaceproduct',
            name='porch_rear_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='marketplaceproduct',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
