# Generated by Django 5.2.4 on 2025-07-25 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0008_marketplaceproduct_included_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceproduct',
            name='area_sqft',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='marketplaceproduct',
            name='area_unit',
            field=models.CharField(choices=[('sqft', 'Square Feet'), ('m2', 'Square Meters')], default='sqft', max_length=10),
        ),
        migrations.AddField(
            model_name='marketplaceproduct',
            name='garage_spaces',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='marketplaceproduct',
            name='main_level_images',
            field=models.JSONField(default=list),
        ),
    ]
